name: "core-plot CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  UnitTests:
    name: Unit Tests
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run unit tests for macOS
        run: xcodebuild -project framework/CorePlot.xcodeproj -target "UnitTests Mac" -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

      - name: Run unit tests for iOS
        run: xcodebuild -project framework/CorePlot.xcodeproj -target "UnitTests iOS" -sdk "iphonesimulator" -destination "name=iPhone 12 Pro" -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

      - name: Run unit tests for tvOS
        run: xcodebuild -project framework/CorePlot.xcodeproj -target "UnitTests tvOS" -sdk "appletvsimulator" -destination "name=Apple TV 4K" -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
        
  SPM:
    name: Verify SPM build
    runs-on: macOS-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    strategy:
      matrix:
        destination:
          [
            "platform=iOS Simulator,name=iPhone 12 Pro",
            "platform=macOS,variant=Mac Catalyst",
            "platform=macOS",
            "platform=tvOS Simulator,name=Apple TV 4k",
          ]
        scheme: ["CorePlot"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate SPM layout
        run: ./scripts/generate_spm_sources_layout.sh

      - name: spm's xcodebuild - ${{ matrix.destination }}
        run: xcodebuild clean build -scheme "${{ matrix.scheme }}" -destination "${{ matrix.destination }}" -configuration Release
